# Generated by Django 5.0.6 on 2026-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreport',
            name='completion_photo_url',
        ),
        migrations.AddField(
            model_name='jobreport',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='job_reports/'),
        ),
    ]
