# Generated by Django 5.0.6 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_jobreport_completion_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Unnamed Device', max_length=255),
        ),
    ]
