# Generated by Django 5.0.6 on 2026-02-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_assigned_at_job_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned')], default='active', max_length=20),
        ),
    ]
